[profile.default]
solc_version = "0.8.24"
src = "contracts"
test = "test"
libs = ["lib"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
